name: df-data-science-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - jupyterlab
  - ipykernel
  - pip
  - pip:
    - plotly
    - nbformat
    - ipywidgets
